"""Insert a visualization cell (sweep-plots) after sweep-summary."""
import json
import sys
from pathlib import Path

nb_path = Path(r"c:/Rust-python-arima/rustima/prac_readme_jihun.ipynb")
nb = json.loads(nb_path.read_text(encoding="utf-8"))

ANCHOR_ID = "sweep-summary"
NEW_ID = "sweep-plots"


def code_cell(cell_id, lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": cell_id,
        "metadata": {},
        "outputs": [],
        "source": lines,
    }


sweep_plots = code_cell(
    NEW_ID,
    [
        "# 시각화 — 대시보드 PNG + 히트맵 + 메모리 타임라인 + HTML 리포트\n",
        "# 실행 전: pip install matplotlib\n",
        "import json\n",
        "import base64\n",
        "from pathlib import Path\n",
        "\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib\n",
        "matplotlib.use(\"Agg\")\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# 한글 폰트 (Windows: Malgun Gothic)\n",
        "plt.rcParams[\"font.family\"] = [\"Malgun Gothic\", \"DejaVu Sans\"]\n",
        "plt.rcParams[\"axes.unicode_minus\"] = False\n",
        "\n",
        "csvs = sorted(Path(\"bench_results\").glob(\"sweep_*/sweep_results.csv\"))\n",
        "assert csvs, \"먼저 sweep-run 셀을 실행해 결과를 생성하세요.\"\n",
        "latest = csvs[-1]\n",
        "out_dir = latest.parent\n",
        "plot_dir = out_dir / \"plots\"\n",
        "tl_dir = plot_dir / \"timelines\"\n",
        "plot_dir.mkdir(exist_ok=True)\n",
        "tl_dir.mkdir(exist_ok=True)\n",
        "print(f\"Source : {latest}\")\n",
        "print(f\"Plots  : {plot_dir}\")\n",
        "\n",
        "df = pd.read_csv(latest)\n",
        "for c in [\"time_s\", \"mem_baseline_mb\", \"mem_peak_mb\", \"mem_delta_mb\"]:\n",
        "    df[c] = pd.to_numeric(df[c], errors=\"coerce\")\n",
        "ok = df[df.status == \"ok\"].copy()\n",
        "ok[\"combo\"] = ok.apply(\n",
        "    lambda r: f\"s{r.s}_sw{int(r.stepwise)}_{r.criterion}_{r.trend}\", axis=1)\n",
        "\n",
        "# ------------------------------------------------------------------\n",
        "# Plot 1: 대시보드 (2x2) — 시간 바차트 / 메모리 바차트 / 스피드업 스캐터 / 분포\n",
        "# ------------------------------------------------------------------\n",
        "rs = ok[ok.library == \"rustima\"].set_index(\"combo\")\n",
        "pm = ok[ok.library == \"pmdarima\"].set_index(\"combo\")\n",
        "common = sorted(rs.index.intersection(pm.index))\n",
        "\n",
        "fig, axes = plt.subplots(2, 2, figsize=(18, 11))\n",
        "\n",
        "# (a) 시간 바차트\n",
        "pivot_t = ok.pivot_table(index=\"combo\", columns=\"library\", values=\"time_s\")\n",
        "pivot_t = pivot_t.reindex(common)\n",
        "pivot_t.plot(kind=\"bar\", ax=axes[0, 0], color=[\"#d9534f\", \"#5bc0de\"])\n",
        "axes[0, 0].set_ylabel(\"time (s)\")\n",
        "axes[0, 0].set_title(\"실행 시간 — 조합별\")\n",
        "axes[0, 0].set_xlabel(\"\")\n",
        "axes[0, 0].tick_params(axis=\"x\", labelrotation=80, labelsize=7)\n",
        "axes[0, 0].grid(axis=\"y\", alpha=0.3)\n",
        "\n",
        "# (b) 피크 메모리 바차트\n",
        "pivot_m = ok.pivot_table(index=\"combo\", columns=\"library\", values=\"mem_peak_mb\")\n",
        "pivot_m = pivot_m.reindex(common)\n",
        "pivot_m.plot(kind=\"bar\", ax=axes[0, 1], color=[\"#d9534f\", \"#5bc0de\"])\n",
        "axes[0, 1].set_ylabel(\"peak RSS (MB)\")\n",
        "axes[0, 1].set_title(\"피크 메모리 — 조합별\")\n",
        "axes[0, 1].set_xlabel(\"\")\n",
        "axes[0, 1].tick_params(axis=\"x\", labelrotation=80, labelsize=7)\n",
        "axes[0, 1].grid(axis=\"y\", alpha=0.3)\n",
        "\n",
        "# (c) 스피드업 vs 메모리 비율 스캐터\n",
        "if common:\n",
        "    speedup = pm.loc[common, \"time_s\"].values / rs.loc[common, \"time_s\"].values\n",
        "    mem_ratio = (pm.loc[common, \"mem_peak_mb\"].values\n",
        "                 / rs.loc[common, \"mem_peak_mb\"].values)\n",
        "    axes[1, 0].scatter(speedup, mem_ratio, alpha=0.6, s=45)\n",
        "    axes[1, 0].axhline(1, color=\"gray\", ls=\"--\", alpha=0.4)\n",
        "    axes[1, 0].axvline(1, color=\"gray\", ls=\"--\", alpha=0.4)\n",
        "    axes[1, 0].set_xlabel(\"speedup  (pmdarima / rustima)\")\n",
        "    axes[1, 0].set_ylabel(\"peak-mem ratio  (pmdarima / rustima)\")\n",
        "    axes[1, 0].set_title(\"rustima 우위 영역 (>1 이면 rustima 가 유리)\")\n",
        "    axes[1, 0].grid(alpha=0.3)\n",
        "\n",
        "# (d) 스피드업 분포\n",
        "if common:\n",
        "    axes[1, 1].hist(speedup, bins=15, color=\"#5cb85c\", alpha=0.8,\n",
        "                    edgecolor=\"black\")\n",
        "    axes[1, 1].axvline(float(np.median(speedup)), color=\"red\", ls=\"--\",\n",
        "                       label=f\"median={np.median(speedup):.1f}x\")\n",
        "    axes[1, 1].set_xlabel(\"speedup (pmdarima / rustima)\")\n",
        "    axes[1, 1].set_ylabel(\"count\")\n",
        "    axes[1, 1].set_title(\"스피드업 분포\")\n",
        "    axes[1, 1].legend()\n",
        "    axes[1, 1].grid(axis=\"y\", alpha=0.3)\n",
        "\n",
        "fig.suptitle(f\"Sweep Dashboard — {out_dir.name}\", fontsize=14, y=1.00)\n",
        "fig.tight_layout()\n",
        "fig.savefig(plot_dir / \"dashboard.png\", dpi=120, bbox_inches=\"tight\")\n",
        "plt.close(fig)\n",
        "print(\"  saved dashboard.png\")\n",
        "\n",
        "# ------------------------------------------------------------------\n",
        "# Plot 2-5: 라이브러리별 히트맵 (time / peak memory)\n",
        "# ------------------------------------------------------------------\n",
        "def _heatmap(subset, metric, title, out_path, cmap=\"viridis\"):\n",
        "    pt = subset.pivot_table(index=[\"seasonal\", \"stepwise\"],\n",
        "                             columns=[\"criterion\", \"trend\"],\n",
        "                             values=metric, aggfunc=\"first\")\n",
        "    if pt.empty:\n",
        "        return\n",
        "    fig, ax = plt.subplots(figsize=(10, 4.5))\n",
        "    im = ax.imshow(pt.values, aspect=\"auto\", cmap=cmap)\n",
        "    ax.set_xticks(range(len(pt.columns)))\n",
        "    ax.set_xticklabels([\"/\".join(map(str, c)) for c in pt.columns],\n",
        "                       rotation=40, ha=\"right\", fontsize=8)\n",
        "    ax.set_yticks(range(len(pt.index)))\n",
        "    ax.set_yticklabels([\"/\".join(map(str, c)) for c in pt.index], fontsize=9)\n",
        "    vmax = np.nanmax(pt.values)\n",
        "    for (j, i), v in np.ndenumerate(pt.values):\n",
        "        if np.isfinite(v):\n",
        "            ax.text(i, j, f\"{v:.1f}\", ha=\"center\", va=\"center\",\n",
        "                    color=\"white\" if v < vmax * 0.5 else \"black\",\n",
        "                    fontsize=7)\n",
        "    fig.colorbar(im, ax=ax)\n",
        "    ax.set_title(title)\n",
        "    ax.set_xlabel(\"criterion / trend\")\n",
        "    ax.set_ylabel(\"seasonal / stepwise\")\n",
        "    fig.tight_layout()\n",
        "    fig.savefig(out_path, dpi=120, bbox_inches=\"tight\")\n",
        "    plt.close(fig)\n",
        "\n",
        "for lib in [\"rustima\", \"pmdarima\"]:\n",
        "    sub = ok[ok.library == lib]\n",
        "    if sub.empty:\n",
        "        continue\n",
        "    _heatmap(sub, \"time_s\", f\"실행 시간 (s) — {lib}\",\n",
        "             plot_dir / f\"heatmap_time_{lib}.png\", cmap=\"magma\")\n",
        "    _heatmap(sub, \"mem_peak_mb\", f\"피크 메모리 (MB) — {lib}\",\n",
        "             plot_dir / f\"heatmap_mem_{lib}.png\", cmap=\"viridis\")\n",
        "print(\"  saved heatmaps\")\n",
        "\n",
        "# ------------------------------------------------------------------\n",
        "# Plot 6: 48 조합 메모리 타임라인 — 한 장(그리드) + 조합별 개별 파일\n",
        "# ------------------------------------------------------------------\n",
        "def _load_samples(mem_file):\n",
        "    p = out_dir / mem_file\n",
        "    if not p.exists():\n",
        "        return [], []\n",
        "    d = json.loads(p.read_text(encoding=\"utf-8\"))\n",
        "    s = d.get(\"samples\") or []\n",
        "    if not s:\n",
        "        return [], []\n",
        "    t, m = zip(*s)\n",
        "    return list(t), list(m)\n",
        "\n",
        "n = len(common)\n",
        "if n:\n",
        "    ncols = 6\n",
        "    nrows = int(np.ceil(n / ncols))\n",
        "    fig_g, axes_g = plt.subplots(nrows, ncols,\n",
        "                                 figsize=(ncols * 3.2, nrows * 2.2),\n",
        "                                 sharex=False)\n",
        "    axes_flat = np.atleast_1d(axes_g).flatten()\n",
        "    for ax in axes_flat[n:]:\n",
        "        ax.axis(\"off\")\n",
        "    for i, combo in enumerate(common):\n",
        "        ax = axes_flat[i]\n",
        "        for lib, color in [(\"rustima\", \"#d9534f\"), (\"pmdarima\", \"#5bc0de\")]:\n",
        "            row = ok[(ok.combo == combo) & (ok.library == lib)]\n",
        "            if row.empty:\n",
        "                continue\n",
        "            t, m = _load_samples(row.iloc[0][\"mem_file\"])\n",
        "            if t:\n",
        "                ax.plot(t, m, color=color, label=lib, lw=1.1)\n",
        "        ax.set_title(combo, fontsize=8)\n",
        "        ax.tick_params(labelsize=6)\n",
        "        ax.grid(alpha=0.25)\n",
        "        if i == 0:\n",
        "            ax.legend(fontsize=7)\n",
        "    fig_g.suptitle(\"메모리 타임라인 — 전체 조합\", fontsize=13, y=1.002)\n",
        "    fig_g.supxlabel(\"elapsed (s)\", fontsize=9)\n",
        "    fig_g.supylabel(\"RSS (MB)\", fontsize=9)\n",
        "    fig_g.tight_layout()\n",
        "    fig_g.savefig(plot_dir / \"timelines_grid.png\", dpi=110, bbox_inches=\"tight\")\n",
        "    plt.close(fig_g)\n",
        "    print(\"  saved timelines_grid.png\")\n",
        "\n",
        "    # 조합별 개별 PNG\n",
        "    for combo in common:\n",
        "        fig, ax = plt.subplots(figsize=(9, 3.6))\n",
        "        for lib, color in [(\"rustima\", \"#d9534f\"), (\"pmdarima\", \"#5bc0de\")]:\n",
        "            row = ok[(ok.combo == combo) & (ok.library == lib)]\n",
        "            if row.empty:\n",
        "                continue\n",
        "            t, m = _load_samples(row.iloc[0][\"mem_file\"])\n",
        "            if t:\n",
        "                peak = row.iloc[0][\"mem_peak_mb\"]\n",
        "                dur = row.iloc[0][\"time_s\"]\n",
        "                ax.plot(t, m, color=color,\n",
        "                        label=f\"{lib}  peak={peak:.1f}MB  time={dur:.2f}s\",\n",
        "                        lw=1.3)\n",
        "        ax.set_xlabel(\"elapsed (s)\")\n",
        "        ax.set_ylabel(\"RSS (MB)\")\n",
        "        ax.set_title(f\"메모리 타임라인 — {combo}\")\n",
        "        ax.legend()\n",
        "        ax.grid(alpha=0.3)\n",
        "        fig.tight_layout()\n",
        "        fig.savefig(tl_dir / f\"timeline_{combo}.png\", dpi=100,\n",
        "                    bbox_inches=\"tight\")\n",
        "        plt.close(fig)\n",
        "    print(f\"  saved {len(common)} per-combo timelines\")\n",
        "\n",
        "# ------------------------------------------------------------------\n",
        "# HTML 리포트 — 모든 PNG 를 base64 인라인 + 테이블 포함\n",
        "# ------------------------------------------------------------------\n",
        "def _img_b64(p):\n",
        "    return base64.b64encode(p.read_bytes()).decode(\"ascii\")\n",
        "\n",
        "html = [\n",
        "    \"<!doctype html><html><head><meta charset='utf-8'>\",\n",
        "    \"<title>Sweep Report</title><style>\",\n",
        "    \"body{font-family:system-ui,'Malgun Gothic',sans-serif;max-width:1400px;margin:20px auto;padding:0 16px;color:#222}\",\n",
        "    \"h1,h2,h3{border-bottom:1px solid #ddd;padding-bottom:4px}\",\n",
        "    \"img{max-width:100%;border:1px solid #ddd;border-radius:4px;margin:8px 0}\",\n",
        "    \"table{border-collapse:collapse;font-size:13px;margin:10px 0}\",\n",
        "    \"th,td{border:1px solid #ccc;padding:4px 8px;text-align:right}\",\n",
        "    \"th{background:#f4f4f4}\",\n",
        "    \"details{margin:8px 0}\",\n",
        "    \"summary{cursor:pointer;font-weight:600}\",\n",
        "    \".kpi{display:flex;gap:24px;flex-wrap:wrap;margin:10px 0}\",\n",
        "    \".kpi div{padding:10px 16px;background:#f8f8f8;border-radius:6px;min-width:140px}\",\n",
        "    \".kpi b{display:block;font-size:20px;color:#0b6}\",\n",
        "    \"</style></head><body>\",\n",
        "    f\"<h1>Sweep Report — {out_dir.name}</h1>\",\n",
        "]\n",
        "\n",
        "n_total = len(df)\n",
        "n_ok = int((df.status == \"ok\").sum())\n",
        "n_fail = int((df.status == \"fail\").sum())\n",
        "med_speedup = float(np.median(speedup)) if common else float(\"nan\")\n",
        "med_mem_ratio = float(np.median(mem_ratio)) if common else float(\"nan\")\n",
        "html.append(\n",
        "    \"<div class='kpi'>\"\n",
        "    f\"<div>총 실행<b>{n_total}</b></div>\"\n",
        "    f\"<div>성공<b>{n_ok}</b></div>\"\n",
        "    f\"<div>실패<b>{n_fail}</b></div>\"\n",
        "    f\"<div>중간 스피드업<b>{med_speedup:.2f}x</b></div>\"\n",
        "    f\"<div>중간 메모리 비율<b>{med_mem_ratio:.2f}x</b></div>\"\n",
        "    \"</div>\"\n",
        ")\n",
        "\n",
        "def _embed(p, title):\n",
        "    if not p.exists():\n",
        "        return\n",
        "    html.append(f\"<h2>{title}</h2>\")\n",
        "    html.append(f\"<img src='data:image/png;base64,{_img_b64(p)}'>\")\n",
        "\n",
        "_embed(plot_dir / \"dashboard.png\", \"대시보드\")\n",
        "for lib in [\"rustima\", \"pmdarima\"]:\n",
        "    _embed(plot_dir / f\"heatmap_time_{lib}.png\", f\"히트맵 · 실행 시간 — {lib}\")\n",
        "    _embed(plot_dir / f\"heatmap_mem_{lib}.png\", f\"히트맵 · 피크 메모리 — {lib}\")\n",
        "_embed(plot_dir / \"timelines_grid.png\", \"메모리 타임라인 — 전체 조합\")\n",
        "\n",
        "if common:\n",
        "    html.append(\"<h2>조합별 메모리 타임라인</h2>\")\n",
        "    for combo in common:\n",
        "        p = tl_dir / f\"timeline_{combo}.png\"\n",
        "        if p.exists():\n",
        "            html.append(f\"<details><summary>{combo}</summary>\"\n",
        "                        f\"<img src='data:image/png;base64,{_img_b64(p)}'></details>\")\n",
        "\n",
        "html.append(\"<h2>원본 결과 테이블</h2>\")\n",
        "html.append(df.to_html(index=False))\n",
        "if n_fail:\n",
        "    html.append(\"<h2>실패 런</h2>\")\n",
        "    html.append(df[df.status == \"fail\"][\n",
        "        [\"idx\", \"library\", \"seasonal\", \"stepwise\", \"criterion\", \"trend\", \"error\"]\n",
        "    ].to_html(index=False))\n",
        "\n",
        "html.append(\"</body></html>\")\n",
        "html_path = out_dir / \"summary.html\"\n",
        "html_path.write_text(\"\\n\".join(html), encoding=\"utf-8\")\n",
        "print(f\"\\n✅ HTML 리포트: {html_path.resolve()}\")\n",
        "print(f\"   브라우저에서 열면 모든 차트/테이블이 한 장에 보입니다.\")"
    ],
)

cells = nb["cells"]
idx = next((i for i, c in enumerate(cells) if c.get("id") == ANCHOR_ID), None)
if idx is None:
    print(f"ERROR: anchor cell id '{ANCHOR_ID}' not found", file=sys.stderr)
    sys.exit(1)

if any(c.get("id") == NEW_ID for c in cells):
    print(f"ERROR: cell id '{NEW_ID}' already exists.", file=sys.stderr)
    sys.exit(2)

cells.insert(idx + 1, sweep_plots)
nb_path.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Inserted '{NEW_ID}' after '{ANCHOR_ID}' (position {idx}).")
