"""Replace sweep-run cell source with a subprocess-isolated, resumable version."""
import json
import sys
from pathlib import Path

nb_path = Path(r"c:/Rust-python-arima/rustima/prac_readme_jihun.ipynb")
nb = json.loads(nb_path.read_text(encoding="utf-8"))
TARGET_ID = "sweep-run"

new_source = [
    "# ======================================================================\n",
    "# 전체 조합 스위프 — subprocess 격리 + Resume 지원 (커널 크래시 방어)\n",
    "#\n",
    "# 방어선:\n",
    "#   1) 각 런을 별도 subprocess 로 실행 → OOM/segfault 가 나도 메인 커널은 살아남음\n",
    "#   2) 완료분은 CSV 에 즉시 기록 → 재실행 시 자동 스킵 (resume)\n",
    "#   3) y 를 y.pkl 로 디스크에 보존 → 커널이 죽어도 이 셀만 다시 실행하면 됨\n",
    "#   4) per-run timeout → 먹통 런 강제 종료 후 다음으로 진행\n",
    "#   5) 워커가 10 샘플마다 mem_json 을 flush → 크래시 직전까지 타임라인 보존\n",
    "# ======================================================================\n",
    "import itertools\n",
    "import subprocess\n",
    "import pickle\n",
    "import csv\n",
    "import json\n",
    "import time\n",
    "import sys\n",
    "import os\n",
    "import textwrap\n",
    "from pathlib import Path\n",
    "from datetime import datetime\n",
    "\n",
    "# ---- 설정 ------------------------------------------------------------\n",
    "SEASONAL_OPTS = [(True, 24), (False, 0)]\n",
    "STEPWISE_OPTS = [True, False]\n",
    "CRITERION_OPTS = [\"aic\", \"bic\", \"hqic\"]\n",
    "TREND_OPTS = [\"n\", \"c\", \"t\", \"ct\"]\n",
    "PER_RUN_TIMEOUT_S = 1800   # 런 당 상한 (30 분) — 데이터가 작으면 줄이세요\n",
    "MEM_INTERVAL_S = 0.05\n",
    "RESUME = True              # True: 가장 최근 미완료 sweep 디렉터리 이어서 실행\n",
    "                           # False: 무조건 새 디렉터리 생성\n",
    "\n",
    "combos = list(itertools.product(SEASONAL_OPTS, STEPWISE_OPTS, CRITERION_OPTS, TREND_OPTS))\n",
    "RUNNERS = [\"rustima\", \"pmdarima\"]\n",
    "total_runs = len(combos) * len(RUNNERS)\n",
    "\n",
    "# ---- 출력 디렉터리 (resume or new) -----------------------------------\n",
    "base = Path(\"bench_results\")\n",
    "base.mkdir(exist_ok=True)\n",
    "\n",
    "FIELDS = [\n",
    "    \"idx\", \"library\", \"seasonal\", \"s\", \"stepwise\", \"criterion\", \"trend\",\n",
    "    \"status\", \"order\", \"seasonal_order\", \"ic_value\",\n",
    "    \"time_s\", \"mem_baseline_mb\", \"mem_peak_mb\", \"mem_delta_mb\",\n",
    "    \"error\", \"log_file\", \"mem_file\",\n",
    "]\n",
    "\n",
    "OUT_DIR = None\n",
    "if RESUME:\n",
    "    for d in sorted(base.glob(\"sweep_*\"), reverse=True):\n",
    "        if (d / \"sweep_results.csv\").exists():\n",
    "            OUT_DIR = d\n",
    "            print(f\"🔁 Resume — 기존 디렉터리 이어서: {OUT_DIR}\")\n",
    "            break\n",
    "if OUT_DIR is None:\n",
    "    STAMP = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "    OUT_DIR = base / f\"sweep_{STAMP}\"\n",
    "    print(f\"🆕 신규 디렉터리: {OUT_DIR}\")\n",
    "\n",
    "LOG_DIR = OUT_DIR / \"logs\"\n",
    "MEM_DIR = OUT_DIR / \"mem_samples\"\n",
    "TMP_DIR = OUT_DIR / \"_tmp\"\n",
    "LOG_DIR.mkdir(parents=True, exist_ok=True)\n",
    "MEM_DIR.mkdir(parents=True, exist_ok=True)\n",
    "TMP_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "csv_path = OUT_DIR / \"sweep_results.csv\"\n",
    "if not csv_path.exists():\n",
    "    with open(csv_path, \"w\", newline=\"\", encoding=\"utf-8\") as f:\n",
    "        csv.DictWriter(f, fieldnames=FIELDS).writeheader()\n",
    "\n",
    "# ---- 완료된 (idx, library) 로드 → 스킵 --------------------------------\n",
    "completed = set()\n",
    "if csv_path.exists():\n",
    "    with open(csv_path, newline=\"\", encoding=\"utf-8\") as f:\n",
    "        for r in csv.DictReader(f):\n",
    "            if r.get(\"status\"):\n",
    "                try:\n",
    "                    completed.add((int(r[\"idx\"]), r[\"library\"]))\n",
    "                except (TypeError, ValueError):\n",
    "                    pass\n",
    "print(f\"이미 완료: {len(completed)} / {total_runs}\")\n",
    "\n",
    "# ---- y 피클 — 커널 재시작 생존 ---------------------------------------\n",
    "Y_PKL = OUT_DIR / \"y.pkl\"\n",
    "if \"y\" in dir():\n",
    "    with open(Y_PKL, \"wb\") as f:\n",
    "        pickle.dump(y, f)\n",
    "    print(f\"y pickled → {Y_PKL}  (len={len(y) if hasattr(y,'__len__') else '?'})\")\n",
    "elif Y_PKL.exists():\n",
    "    print(f\"⚠️  현재 커널에 y 미정의. 기존 y.pkl 재사용: {Y_PKL}\")\n",
    "else:\n",
    "    raise RuntimeError(\n",
    "        f\"y 가 커널에도 없고 {Y_PKL} 도 없습니다. 데이터 로딩 셀을 먼저 실행하세요.\")\n",
    "\n",
    "# ---- 워커 스크립트 생성 ----------------------------------------------\n",
    "WORKER = OUT_DIR / \"_worker.py\"\n",
    "WORKER.write_text(textwrap.dedent(r'''\n",
    "    import sys, os, time, json, pickle, threading, traceback, gc\n",
    "    (tag, lib, s, stepwise, criterion, trend, y_pkl, result_json,\n",
    "     mem_json, log_txt, interval) = sys.argv[1:12]\n",
    "    s = int(s); stepwise = stepwise == \"1\"; interval = float(interval)\n",
    "\n",
    "    import psutil\n",
    "    proc = psutil.Process(os.getpid())\n",
    "\n",
    "    # --- 주기적 flush 가능한 memory sampler ---\n",
    "    stop = threading.Event()\n",
    "    samples = []\n",
    "    baseline = proc.memory_info().rss / 1024 ** 2\n",
    "    peak = [baseline]\n",
    "\n",
    "    def _flush_mem():\n",
    "        with open(mem_json, \"w\", encoding=\"utf-8\") as f:\n",
    "            json.dump({\"tag\": tag, \"baseline_mb\": baseline,\n",
    "                       \"peak_mb\": peak[0], \"delta_mb\": peak[0] - baseline,\n",
    "                       \"interval_s\": interval, \"samples\": samples,\n",
    "                       \"partial\": not stop.is_set()}, f)\n",
    "\n",
    "    def _sampler():\n",
    "        t0 = time.perf_counter()\n",
    "        samples.append((0.0, baseline))\n",
    "        i = 0\n",
    "        while not stop.is_set():\n",
    "            m = proc.memory_info().rss / 1024 ** 2\n",
    "            samples.append((time.perf_counter() - t0, m))\n",
    "            if m > peak[0]: peak[0] = m\n",
    "            i += 1\n",
    "            if i % 10 == 0:\n",
    "                try: _flush_mem()\n",
    "                except Exception: pass\n",
    "            stop.wait(interval)\n",
    "\n",
    "    th = threading.Thread(target=_sampler, daemon=True)\n",
    "    th.start()\n",
    "\n",
    "    # --- 데이터 로드 ---\n",
    "    with open(y_pkl, \"rb\") as f:\n",
    "        y = pickle.load(f)\n",
    "\n",
    "    # --- 본 실행 ---\n",
    "    import io, contextlib\n",
    "    buf = io.StringIO()\n",
    "    status, err = \"ok\", \"\"\n",
    "    order = seasonal_order = ic_val = None\n",
    "    elapsed = None\n",
    "    try:\n",
    "        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(buf):\n",
    "            t0 = time.perf_counter()\n",
    "            if lib == \"rustima\":\n",
    "                from rustima import auto_arima as rs_auto_arima\n",
    "                res = rs_auto_arima(y, s=s, trend=trend, stepwise=stepwise,\n",
    "                                    trace=True, criterion=criterion)\n",
    "                order = str(tuple(res.order))\n",
    "                so = getattr(res, \"seasonal_order\", None)\n",
    "                seasonal_order = str(tuple(so)) if so is not None else \"\"\n",
    "                ic_val = getattr(res.result, criterion, None)\n",
    "            else:\n",
    "                import pmdarima as pm\n",
    "                res = pm.auto_arima(\n",
    "                    y, seasonal=(s > 0), m=s if s > 0 else 1, trend=trend,\n",
    "                    stepwise=stepwise, suppress_warnings=True,\n",
    "                    information_criterion=criterion, trace=True)\n",
    "                order = str(tuple(res.order))\n",
    "                seasonal_order = str(tuple(res.seasonal_order))\n",
    "                getter = getattr(res, criterion, None)\n",
    "                ic_val = getter() if callable(getter) else None\n",
    "            elapsed = time.perf_counter() - t0\n",
    "    except Exception as e:\n",
    "        status = \"fail\"\n",
    "        err = f\"{type(e).__name__}: {e}\"\n",
    "        traceback.print_exc(file=buf)\n",
    "\n",
    "    stop.set(); th.join()\n",
    "    _flush_mem()\n",
    "    with open(log_txt, \"w\", encoding=\"utf-8\") as f:\n",
    "        f.write(buf.getvalue())\n",
    "    with open(result_json, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump({\"status\": status, \"error\": err,\n",
    "                   \"order\": order or \"\", \"seasonal_order\": seasonal_order or \"\",\n",
    "                   \"ic_value\": ic_val if isinstance(ic_val, (int, float)) else None,\n",
    "                   \"time_s\": elapsed,\n",
    "                   \"mem_baseline_mb\": baseline,\n",
    "                   \"mem_peak_mb\": peak[0],\n",
    "                   \"mem_delta_mb\": peak[0] - baseline}, f)\n",
    "'''), encoding=\"utf-8\")\n",
    "\n",
    "# ---- 메인 루프 --------------------------------------------------------\n",
    "sweep_t0 = time.perf_counter()\n",
    "run_i = 0\n",
    "for idx, ((seasonal, s), stepwise, criterion, trend) in enumerate(combos):\n",
    "    for lib_name in RUNNERS:\n",
    "        run_i += 1\n",
    "        if (idx, lib_name) in completed:\n",
    "            continue\n",
    "        tag = f\"{idx:02d}_{lib_name}_s{s}_sw{int(stepwise)}_{criterion}_{trend}\"\n",
    "        print(f\"\\n{'=' * 80}\")\n",
    "        print(f\"[{run_i:03d}/{total_runs}] {lib_name}  seasonal={seasonal}(s={s}) \"\n",
    "              f\"stepwise={stepwise} crit={criterion} trend={trend}\")\n",
    "        print(\"=\" * 80)\n",
    "\n",
    "        result_json = TMP_DIR / f\"{tag}.result.json\"\n",
    "        mem_path = MEM_DIR / f\"{tag}.json\"\n",
    "        log_path = LOG_DIR / f\"{tag}.log\"\n",
    "\n",
    "        cmd = [sys.executable, str(WORKER), tag, lib_name, str(s),\n",
    "               \"1\" if stepwise else \"0\", criterion, trend,\n",
    "               str(Y_PKL), str(result_json), str(mem_path), str(log_path),\n",
    "               str(MEM_INTERVAL_S)]\n",
    "\n",
    "        row = {k: \"\" for k in FIELDS}\n",
    "        row.update({\"idx\": idx, \"library\": lib_name, \"seasonal\": seasonal,\n",
    "                    \"s\": s, \"stepwise\": stepwise, \"criterion\": criterion,\n",
    "                    \"trend\": trend,\n",
    "                    \"log_file\": str(log_path.relative_to(OUT_DIR)),\n",
    "                    \"mem_file\": str(mem_path.relative_to(OUT_DIR))})\n",
    "        try:\n",
    "            cp = subprocess.run(cmd, timeout=PER_RUN_TIMEOUT_S,\n",
    "                                capture_output=True, text=True,\n",
    "                                encoding=\"utf-8\", errors=\"replace\")\n",
    "            if result_json.exists():\n",
    "                d = json.loads(result_json.read_text(encoding=\"utf-8\"))\n",
    "                row[\"status\"] = d.get(\"status\", \"ok\")\n",
    "                row[\"error\"] = (d.get(\"error\") or \"\")[:500]\n",
    "                row[\"order\"] = d.get(\"order\", \"\")\n",
    "                row[\"seasonal_order\"] = d.get(\"seasonal_order\", \"\")\n",
    "                ic = d.get(\"ic_value\")\n",
    "                row[\"ic_value\"] = f\"{ic:.4f}\" if isinstance(ic, (int, float)) else \"\"\n",
    "                t_s = d.get(\"time_s\")\n",
    "                row[\"time_s\"] = f\"{t_s:.4f}\" if isinstance(t_s, (int, float)) else \"\"\n",
    "                for k in (\"mem_baseline_mb\", \"mem_peak_mb\", \"mem_delta_mb\"):\n",
    "                    v = d.get(k)\n",
    "                    row[k] = f\"{v:.2f}\" if isinstance(v, (int, float)) else \"\"\n",
    "                try: result_json.unlink()\n",
    "                except OSError: pass\n",
    "            else:\n",
    "                row[\"status\"] = \"crashed\"\n",
    "                tail = (cp.stderr or cp.stdout or \"\").splitlines()[-5:]\n",
    "                row[\"error\"] = (\" | \".join(tail))[:500]\n",
    "                with open(log_path, \"a\", encoding=\"utf-8\") as f:\n",
    "                    f.write(f\"\\n--- SUBPROCESS CRASH (exit={cp.returncode}) ---\\n\")\n",
    "                    f.write(\"STDOUT:\\n\" + (cp.stdout or \"\") + \"\\n\")\n",
    "                    f.write(\"STDERR:\\n\" + (cp.stderr or \"\") + \"\\n\")\n",
    "        except subprocess.TimeoutExpired:\n",
    "            row[\"status\"] = \"timeout\"\n",
    "            row[\"error\"] = f\"exceeded {PER_RUN_TIMEOUT_S}s\"\n",
    "            with open(log_path, \"a\", encoding=\"utf-8\") as f:\n",
    "                f.write(f\"\\n--- TIMEOUT after {PER_RUN_TIMEOUT_S}s ---\\n\")\n",
    "        except Exception as e:\n",
    "            row[\"status\"] = \"launch_fail\"\n",
    "            row[\"error\"] = f\"{type(e).__name__}: {e}\"\n",
    "\n",
    "        with open(csv_path, \"a\", newline=\"\", encoding=\"utf-8\") as f:\n",
    "            csv.DictWriter(f, fieldnames=FIELDS).writerow(row)\n",
    "        print(f\"-> [{row['status']}] order={row['order']} \"\n",
    "              f\"ic={row['ic_value']} time={row['time_s']}s \"\n",
    "              f\"peak={row['mem_peak_mb']}MB\")\n",
    "        if row[\"error\"]:\n",
    "            print(f\"   err: {row['error'][:200]}\")\n",
    "        completed.add((idx, lib_name))\n",
    "\n",
    "elapsed = time.perf_counter() - sweep_t0\n",
    "print(f\"\\n✅ 세션 종료 — 누적 완료 {len(completed)}/{total_runs}, \"\n",
    "      f\"이번 세션 {elapsed/60:.1f}분 소요\")\n",
    "print(f\"   CSV : {csv_path}\")\n",
    "print(f\"   로그 : {LOG_DIR}\")\n",
    "print(f\"   메모리 : {MEM_DIR}\")\n",
    "print(f\"   재실행 시 완료분은 자동 스킵됩니다.\")"
]

cells = nb["cells"]
idx = next((i for i, c in enumerate(cells) if c.get("id") == TARGET_ID), None)
if idx is None:
    print(f"ERROR: cell id '{TARGET_ID}' not found", file=sys.stderr)
    sys.exit(1)

cells[idx]["source"] = new_source
cells[idx]["outputs"] = []
cells[idx]["execution_count"] = None
nb_path.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Replaced source of cell id='{TARGET_ID}' (position {idx}).")
